package com.rodrigodev.xgen.test.integration.common.appliance.discharged;

import com.rodrigodev.xgen.test.integration.common.appliance.ApplianceException;
import com.rodrigodev.xgen.test.integration.HouseException;

/**
 * Autogenerated by XGen on July 11, 2015.
 */
public class DischargedException extends ApplianceException {



    protected DischargedException(String message) {
        super(message);
    }

    protected DischargedException(String message, Throwable cause) {
        super(message, cause);
    }
}
