package com.rodrigodev.xgen.test.organization.hierarchy.e1.e2;

import com.rodrigodev.xgen.test.organization.hierarchy.e1.E1Error;
import com.rodrigodev.xgen.test.organization.hierarchy.ErrorCode;


/**
* Autogenerated by XGen on July 2, 2015.
*/
public abstract class E2Error extends E1Error {

    public static final ErrorCode CODE = new ErrorCode("e-2", E1Error.CODE);

}
