package com.rodrigodev.xgen.test.integration.kitchen.oven.undercooked;

import com.rodrigodev.xgen.test.integration.kitchen.oven.OvenException;

/**
* Autogenerated by XGen on June 28, 2015.
*/
public class UndercookedException extends OvenException {

    protected UndercookedException(String message) {
        super(message);
    }
}
