package com.rodrigodev.xgen.test.integration.common.room.bad_smell;

import com.rodrigodev.xgen.test.integration.common.room.RoomException;
import com.rodrigodev.xgen.test.integration.HouseException;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public class BadSmellException extends RoomException {



    protected BadSmellException(String message) {
        super(message);
    }

    protected BadSmellException(String message, Throwable cause) {
        super(message, cause);
    }
}
