package com.rodrigodev.xgen4j.test.integration.common.room.bad_smell;

import com.rodrigodev.xgen4j.test.integration.common.room.RoomException;
import com.rodrigodev.xgen4j.test.integration.HouseException;
import com.rodrigodev.xgen4j.test.integration.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class BadSmellException extends RoomException {

    protected BadSmellException(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected BadSmellException(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
