package com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified_mixedCase.c1;

import com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified_mixedCase.RootNameException;

/**
* Autogenerated by XGen on June 29, 2015.
*/
public class C1Exception extends RootNameException {

    protected C1Exception(String message) {
        super(message);
    }
}
