package com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_withNumber;

import com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_withNumber.BRootException.ExceptionType;
import java.util.Optional;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public class ExceptionInfo {

    final private Class<? extends BRootException> clazz;
    final private Optional<ExceptionType> type;

    private ExceptionInfo(Optional<ExceptionType> type, Class<? extends BRootException> clazz) {
        this.type = type;
        this.clazz = clazz;
    }

    public ExceptionInfo(Class<? extends BRootException> clazz) {
        this(Optional.empty(), clazz);
    }

    public ExceptionInfo(ExceptionType type, Class<? extends BRootException> clazz) {
        this(Optional.of(type), clazz);
    }

    public Class<? extends BRootException> clazz() {
        return clazz;
    }

    public Optional<ExceptionType> type() {
        return type;
    }
}
