package com.rodrigodev.xgen.test.message.descriptionWithCustomObjectThatGeneratesTheMessageCanBeUsed.e1.e2;

import com.rodrigodev.xgen.test.message.descriptionWithCustomObjectThatGeneratesTheMessageCanBeUsed.e1.E1Exception;

/**
* Autogenerated by XGen on July 2, 2015.
*/
public class E2Exception extends E1Exception {

    protected E2Exception(String message) {
        super(message);
    }
}
