package com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract.c1.c2;

import com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract.c1.C1Exception;

/**
* Autogenerated by XGen on July 3, 2015.
*/
public class C2Exception extends C1Exception {

    protected C2Exception(String message) {
        super(message);
    }
}
