package com.rodrigodev.xgen.test.info_generation.ea1.ea2;

import com.rodrigodev.xgen.test.info_generation.ea1.EA1Error;


import com.rodrigodev.xgen.test.info_generation.ErrorCode;

/**
 * Autogenerated by XGen on July 12, 2015.
 */
public abstract class EA2Error extends EA1Error {

    public static final ErrorCode CODE = new ErrorCode("e-a-2", EA1Error.CODE);


}
