package com.rodrigodev.xgen.test.organization.packages.common_name1;

import com.rodrigodev.xgen.test.organization.packages.RootNameError;
import com.rodrigodev.xgen.test.organization.packages.ErrorCode;


/**
* Autogenerated by XGen on June 28, 2015.
*/
public abstract class CommonName1Error extends RootNameError {

    public static final ErrorCode CODE = new ErrorCode("root-name.common-name-1");

}
