package com.rodrigodev.xgen.test.code.codeNumericIdAndNumberAreGeneratedWhenNameIsAlsoSpecifiedSpecified.e1.e2.e3_2;

import com.rodrigodev.xgen.test.code.codeNumericIdAndNumberAreGeneratedWhenNameIsAlsoSpecifiedSpecified.e1.e2.E2Exception;

/**
* Autogenerated by XGen on July 2, 2015.
*/
public class E3_2Exception extends E2Exception {

    protected E3_2Exception(String message) {
        super(message);
    }
}
