package com.rodrigodev.xgen4j.test.info_generation.ea1.ea2;

import com.rodrigodev.xgen4j.test.info_generation.ea1.EA1Exception;
import com.rodrigodev.xgen4j.test.info_generation.RootException;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public class EA2Exception extends EA1Exception {

    public static final ExceptionType TYPE = new ExceptionType();

    private static class ExceptionType extends RootException.ExceptionType {

        @Override
        protected RootException createException(String message) {
            return new EA2Exception(message);
        }

        @Override
        protected RootException createException(String message, Throwable cause) {
            return new EA2Exception(message, cause);
        }
    }

    protected EA2Exception(String message) {
        super(message);
    }

    protected EA2Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
