package com.rodrigodev.xgen.test.code.codeIdIsGenerated.e1.e2.e3_2;

import com.rodrigodev.xgen.test.code.codeIdIsGenerated.e1.e2.E2Error;
import com.rodrigodev.xgen.test.code.codeIdIsGenerated.ErrorCode;


/**
* Autogenerated by XGen on July 1, 2015.
*/
public abstract class E3_2Error extends E2Error {

    public static final ErrorCode CODE = new ErrorCode("code-name-root.code-name-e1.code-name-e2.code-name-e3-2");

    private static String MESSAGE_FORMAT = "ABCDE";

    public static void throwException() {
        throw new E3_2Exception(String.format(MESSAGE_FORMAT));
    }
}
