package com.rodrigodev.xgen.test.info_generation.ea1.ea2.ea3_3;

import com.rodrigodev.xgen.test.info_generation.ea1.ea2.EA2Exception;
import com.rodrigodev.xgen.test.info_generation.RootException;

/**
 * Autogenerated by XGen on July 12, 2015.
 */
public class EA3_3Exception extends EA2Exception {

    public static final ExceptionType TYPE = new ExceptionType();

    private static class ExceptionType extends RootException.ExceptionType {

        @Override
        protected RootException createException(String message) {
            return new EA3_3Exception(message);
        }

        @Override
        protected RootException createException(String message, Throwable cause) {
            return new EA3_3Exception(message, cause);
        }
    }

    protected EA3_3Exception(String message) {
        super(message);
    }

    protected EA3_3Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
