package com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNoNumericId.cname1.cname2.cname3_3;

import com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNoNumericId.cname1.cname2.CName2Exception;
import com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNoNumericId.RootNameException;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public class CName3_3Exception extends CName2Exception {



    protected CName3_3Exception(String message) {
        super(message);
    }

    protected CName3_3Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
