package com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract.e1.e2;

import com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract.e1.E1Error;


import com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract.ErrorCode;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public abstract class E2Error extends E1Error {

    public static final ErrorCode CODE = new ErrorCode("e-2", E1Error.CODE);


}
