package com.rodrigodev.xgen.test.code.errorCodeEqualityIsBasedOnId_withNumber;




/**
 * Autogenerated by XGen on July 11, 2015.
 */
public class BRootException extends RuntimeException {


    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract BRootException createException(String message);

        protected abstract BRootException createException(String message, Throwable cause);
    }

    protected BRootException(String message) {
        super(message);
    }

    protected BRootException(String message, Throwable cause) {
        super(message, cause);
    }
}
