package com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified_mixedCase.e1.error_name2.error_name3_3;

import com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified_mixedCase.e1.error_name2.ErrorName2Exception;

/**
* Autogenerated by XGen on June 30, 2015.
*/
public class ErrorName3_3Exception extends ErrorName2Exception {

    protected ErrorName3_3Exception(String message) {
        super(message);
    }
}
