package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.e1;

import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.RootNameError;


import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.ErrorCode;

/**
* Autogenerated by XGen on July 6, 2015.
*/
public abstract class E1Error extends RootNameError {

    public static final ErrorCode CODE = new ErrorCode("code-name-e1", RootNameError.CODE);


}
