package com.rodrigodev.xgen4j.test.generation_options.checkedExceptionsAreGeneratedWhenCorrespondingOptionIsSet.cc1.cc2.cc3_3;

import com.rodrigodev.xgen4j.test.generation_options.checkedExceptionsAreGeneratedWhenCorrespondingOptionIsSet.cc1.cc2.CC2Error;

import com.rodrigodev.xgen4j.test.common.doubles.error.message.TestMessageGeneratorObject;

import com.rodrigodev.xgen4j.test.generation_options.checkedExceptionsAreGeneratedWhenCorrespondingOptionIsSet.ErrorCode;
import com.rodrigodev.xgen4j.test.generation_options.checkedExceptionsAreGeneratedWhenCorrespondingOptionIsSet.CRootException;
import com.rodrigodev.xgen4j.test.generation_options.checkedExceptionsAreGeneratedWhenCorrespondingOptionIsSet.CRootException.ExceptionType;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public abstract class CC3_3Error extends CC2Error {

    public static final ErrorCode CODE = new ErrorCode("c-c-3-3", CC2Error.CODE);

    private static String createMessage(TestMessageGeneratorObject generator) {
        if(generator == null) throw new NullPointerException("generator");

        return generator.message();
    }

    public static void throwException(TestMessageGeneratorObject generator) throws CC3_3Exception {
        throw new CC3_3Exception(CODE, createMessage(generator));
    }

    public static void throwException(TestMessageGeneratorObject generator, Throwable cause) throws CC3_3Exception {
        throw new CC3_3Exception(CODE, createMessage(generator), cause);
    }

    public static void throwException(ExceptionType exceptionType, TestMessageGeneratorObject generator) throws CRootException {
        throwExceptionForCommonError(CODE, exceptionType, createMessage(generator));
    }

    public static void throwException(ExceptionType exceptionType, TestMessageGeneratorObject generator, Throwable cause) throws CRootException {
        throwExceptionForCommonError(CODE, exceptionType, createMessage(generator), cause);
    }

}
