package com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed.c1;

import com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed.RootError;


import com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed.ErrorCode;
import com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed.RootException.ExceptionType;

/**
 * Autogenerated by XGen on July 11, 2015.
 */
public abstract class C1Error extends RootError {

    public static final ErrorCode CODE = new ErrorCode("c-1", RootError.CODE);


}
