package com.rodrigodev.xgen.test.message.descriptionWithMultipleParametersIsAllowed.c1.c2;

import com.rodrigodev.xgen.test.message.descriptionWithMultipleParametersIsAllowed.c1.C1Error;


import com.rodrigodev.xgen.test.message.descriptionWithMultipleParametersIsAllowed.ErrorCode;
import com.rodrigodev.xgen.test.message.descriptionWithMultipleParametersIsAllowed.RootException.ExceptionType;

/**
 * Autogenerated by XGen on July 12, 2015.
 */
public abstract class C2Error extends C1Error {

    public static final ErrorCode CODE = new ErrorCode("c-2", C1Error.CODE);


}
