package com.rodrigodev.xgen.test.organization.packages.common_name1.common_name2.common_name3_2;

import com.rodrigodev.xgen.test.organization.packages.common_name1.common_name2.CommonName2Exception;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class CommonName3_2Exception extends CommonName2Exception {

    protected CommonName3_2Exception(String message) {
        super(message);
    }
}
