package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified.error_name1;

import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified.RootNameError;


import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified.ErrorCode;

/**
* Autogenerated by XGen on July 4, 2015.
*/
public abstract class ErrorName1Error extends RootNameError {

    public static final ErrorCode CODE = new ErrorCode("error-name-1", RootNameError.CODE);


}
