package com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores;


import com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores.ErrorCode;


/**
* Autogenerated by XGen on July 1, 2015.
*/
public abstract class Root_name7Error {

    public static final ErrorCode CODE = new ErrorCode("root-name-7");

}
