package com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores;




import com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores.Root_Name2_Exception.ExceptionType;

/**
* Autogenerated by XGen on July 4, 2015.
*/
public abstract class Root_Name2_Error {

    public static final ErrorCode CODE = new ErrorCode("root-name-2");


    protected static void throwExceptionForCommonError(ExceptionType exceptionType, String message) {
        throw exceptionType.createException(message);
    }
}
