package com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores;



/**
* Autogenerated by XGen on June 28, 2015.
*/
public class RootName10___Exception extends RuntimeException {

    protected RootName10___Exception(String message) {
        super(message);
    }
}
