package com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores;


import com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores.ErrorCode;


/**
* Autogenerated by XGen on June 30, 2015.
*/
public abstract class RootName6_Error {

    public static final ErrorCode CODE = new ErrorCode("root-name-6");

}
