package com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores;



/**
* Autogenerated by XGen on June 30, 2015.
*/
public class RootName9__Exception extends RuntimeException {

    protected RootName9__Exception(String message) {
        super(message);
    }
}
