package com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores;



/**
* Autogenerated by XGen on June 28, 2015.
*/
public class Root_name11Exception extends RuntimeException {

    protected Root_name11Exception(String message) {
        super(message);
    }
}
