package com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores;




import com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores.Root___Name5___Exception.ExceptionType;

/**
* Autogenerated by XGen on July 4, 2015.
*/
public abstract class Root___Name5___Error {

    public static final ErrorCode CODE = new ErrorCode("root-name-5");


    protected static void throwExceptionForCommonError(ExceptionType exceptionType, String message) {
        throw exceptionType.createException(message);
    }
}
