package com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores;



/**
* Autogenerated by XGen on June 30, 2015.
*/
public class Root_name7Exception extends RuntimeException {

    protected Root_name7Exception(String message) {
        super(message);
    }
}
