package com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores;




/**
* Autogenerated by XGen on July 6, 2015.
*/
public class Root_name7Exception extends RuntimeException {

    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract Root_name7Exception createException(String message);
    }

    protected Root_name7Exception(String message) {
        super(message);
    }
}
