package com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores;



/**
* Autogenerated by XGen on July 3, 2015.
*/
public class Root__Name3__Exception extends RuntimeException {

    protected Root__Name3__Exception(String message) {
        super(message);
    }
}
