package com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores;



/**
* Autogenerated by XGen on June 29, 2015.
*/
public class Root__Name3Exception extends RuntimeException {

    protected Root__Name3Exception(String message) {
        super(message);
    }
}
