package com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores;



/**
* Autogenerated by XGen on June 28, 2015.
*/
public class RootName6_Exception extends RuntimeException {

    protected RootName6_Exception(String message) {
        super(message);
    }
}
