package com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores;


import com.rodrigodev.xgen.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores.ErrorCode;


/**
* Autogenerated by XGen on June 29, 2015.
*/
public abstract class RootName10___Error {

    public static final ErrorCode CODE = new ErrorCode("root-name-10");

}
