package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class AlarmClockException extends BedroomException {

    protected AlarmClockException(String message) {
        super(message);
    }
}
