package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class BadSmellException extends RoomException {

    protected BadSmellException(String message) {
        super(message);
    }
}
