package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 12/05/15.
*/
public class BedError extends BedroomError {

    private static String MESSAGE_FORMAT = "This bed is freaking bad. Model: %s";

    public static void throwException(String model) {
        throw new BedException(String.format(MESSAGE_FORMAT, model));
    }
}
