package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class BedIsWarmException extends BedException {

    protected BedIsWarmException(String message) {
        super(message);
    }
}
