package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class BurnedFoodException extends RuntimeException {

    protected BurnedFoodException(String message) {
        super(message);
    }
}
