package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 12/05/15.
*/
public class DidNotSoundError {

    private static String MESSAGE_FORMAT = "Oh shooooot!!! Now WTF am I supposed to do? %s is going to fire me!";

    public static void throwException(String bossName) {
        throw new DidNotSoundException(String.format(MESSAGE_FORMAT, bossName));
    }
}
