package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class DirtyException extends RuntimeException {

    protected DirtyException(String message) {
        super(message);
    }
}
