package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class FrozenFoodException extends FridgeException {

    protected FrozenFoodException(String message) {
        super(message);
    }
}
