package com.rodrigodev.xgen.test.integration;



/**
* Autogenerated by XGen on June 29, 2015.
*/
public class HouseException extends RuntimeException {

    protected HouseException(String message) {
        super(message);
    }
}
