package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class KitchenException extends RuntimeException {

    protected KitchenException(String message) {
        super(message);
    }
}
