package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 12/05/15.
*/
public class OvenError extends KitchenError {

    private static String MESSAGE_FORMAT = "The oven is not working. Model: %s";

    public static void throwException(String model) {
        throw new OvenException(String.format(MESSAGE_FORMAT, model));
    }
}
