package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class PillowNotFoundException extends BedException {

    protected PillowNotFoundException(String message) {
        super(message);
    }
}
