package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class RoomException extends RuntimeException {

    protected RoomException(String message) {
        super(message);
    }
}
