package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class RottenFoodException extends FridgeException {

    protected RottenFoodException(String message) {
        super(message);
    }
}
