package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class TooSmallException extends RuntimeException {

    protected TooSmallException(String message) {
        super(message);
    }
}
