package com.rodrigodev.xgen.test.integration;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class UndercookedException extends OvenException {

    protected UndercookedException(String message) {
        super(message);
    }
}
