package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedWhenSpecified;




import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedWhenSpecified.RootException.ExceptionType;

/**
* Autogenerated by XGen on July 4, 2015.
*/
public abstract class RootError {

    public static final ErrorCode CODE = new ErrorCode("code-name-root");


    protected static void throwExceptionForCommonError(ExceptionType exceptionType, String message) {
        throw exceptionType.createException(message);
    }
}
