package com.rodrigodev.xgen.test.integration.kitchen.fridge.frozen_food;

import com.rodrigodev.xgen.test.integration.kitchen.fridge.FridgeException;
import com.rodrigodev.xgen.test.integration.HouseException;

/**
* Autogenerated by XGen on July 4, 2015.
*/
public class FrozenFoodException extends FridgeException {

    public static final ExceptionType TYPE = new ExceptionType();

    private static class ExceptionType extends HouseException.ExceptionType {

        @Override
        protected HouseException createException(String message) {
            return new FrozenFoodException(message);
        }
    }

    protected FrozenFoodException(String message) {
        super(message);
    }
}
