package com.rodrigodev.xgen.test.integration.kitchen.fridge.frozen_food;

import com.rodrigodev.xgen.test.integration.kitchen.fridge.FridgeException;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class FrozenFoodException extends FridgeException {

    protected FrozenFoodException(String message) {
        super(message);
    }
}
