package com.rodrigodev.xgen4j.test.integration.bedroom;

import com.rodrigodev.xgen4j.test.integration.HouseException;
import com.rodrigodev.xgen4j.test.integration.HouseException;
import com.rodrigodev.xgen4j.test.integration.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class BedroomException extends HouseException {

    public static final ExceptionType TYPE = new ExceptionType();

    protected BedroomException(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected BedroomException(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }

    private static class ExceptionType extends HouseException.ExceptionType {

        @Override
        protected HouseException createException(ErrorCode errorCode, String message) {
            return new BedroomException(errorCode, message);
        }

        @Override
        protected HouseException createException(ErrorCode errorCode, String message, Throwable cause) {
            return new BedroomException(errorCode, message, cause);
        }
    }
}
