package com.rodrigodev.xgen.test.message.descriptionWithMultipleParametersIsAllowed.e1;

import com.rodrigodev.xgen.test.message.descriptionWithMultipleParametersIsAllowed.RootError;


import com.rodrigodev.xgen.test.message.descriptionWithMultipleParametersIsAllowed.ErrorCode;

/**
* Autogenerated by XGen on July 8, 2015.
*/
public abstract class E1Error extends RootError {

    public static final ErrorCode CODE = new ErrorCode("e-1", RootError.CODE);


}
