package com.rodrigodev.xgen.test.code.codeNumericIdAndNumberAreGeneratedWhenSpecified.c1.c2.c3_1;

import com.rodrigodev.xgen.test.code.codeNumericIdAndNumberAreGeneratedWhenSpecified.c1.c2.C2Error;


import com.rodrigodev.xgen.test.code.codeNumericIdAndNumberAreGeneratedWhenSpecified.ErrorCode;
import com.rodrigodev.xgen.test.code.codeNumericIdAndNumberAreGeneratedWhenSpecified.RootException.ExceptionType;

/**
* Autogenerated by XGen on July 6, 2015.
*/
public abstract class C3_1Error extends C2Error {

    public static final ErrorCode CODE = new ErrorCode("c-3-1", 456, C2Error.CODE);

    private static String MESSAGE_FORMAT = "ABCDE";

    private static String createMessage() {
        return String.format(MESSAGE_FORMAT);
    }

    public static void throwException() {

        throw new C3_1Exception(createMessage());
    }

    public static void throwException(ExceptionType exceptionType) {

        throwExceptionForCommonError(exceptionType, createMessage());
    }

}
