package com.rodrigodev.xgen4j.test.code.codeNameCanBeEqualToRootCodeNameForErrorsThatAreNotChildrenOfRootError_nameOnly.code_name_c1.code_name_root.code_name_root;

import com.rodrigodev.xgen4j.test.code.codeNameCanBeEqualToRootCodeNameForErrorsThatAreNotChildrenOfRootError_nameOnly.code_name_c1.code_name_root.C2Exception;
import com.rodrigodev.xgen4j.test.code.codeNameCanBeEqualToRootCodeNameForErrorsThatAreNotChildrenOfRootError_nameOnly.RootException;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class C3Exception extends C2Exception {



    protected C3Exception(String message) {
        super(message);
    }

    protected C3Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
