package com.rodrigodev.xgen4j.test.info_generation.methodForRetrievingErrorInfoByItsNumericIdIsNotGeneratedWhenErrorCodeDoesNotHaveNumericId.c1.c2;

import com.rodrigodev.xgen4j.test.info_generation.methodForRetrievingErrorInfoByItsNumericIdIsNotGeneratedWhenErrorCodeDoesNotHaveNumericId.c1.C1Exception;
import com.rodrigodev.xgen4j.test.info_generation.methodForRetrievingErrorInfoByItsNumericIdIsNotGeneratedWhenErrorCodeDoesNotHaveNumericId.RootException;
import com.rodrigodev.xgen4j.test.info_generation.methodForRetrievingErrorInfoByItsNumericIdIsNotGeneratedWhenErrorCodeDoesNotHaveNumericId.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class C2Exception extends C1Exception {

    protected C2Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected C2Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
