package com.rodrigodev.xgen4j.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsSetAsFalse.u2_c1;

import com.rodrigodev.xgen4j.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsSetAsFalse.U2RootException;
import com.rodrigodev.xgen4j.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsSetAsFalse.U2RootException;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class U2C1Exception extends U2RootException {



    protected U2C1Exception(String message) {
        super(message);
    }

    protected U2C1Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
