package com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsSetAsFalse.u2c1.u2c2.u2c3_3;

import com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsSetAsFalse.u2c1.u2c2.U2C2Exception;
import com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsSetAsFalse.U2RootException;

/**
 * Autogenerated by XGen on July 13, 2015.
 */
public class U2C3_3Exception extends U2C2Exception {



    protected U2C3_3Exception(String message) {
        super(message);
    }

    protected U2C3_3Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
