package com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_onlyName.c1.c2;

import com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_onlyName.c1.AC1Exception;
import com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_onlyName.ARootException;
import com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_onlyName.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class AC2Exception extends AC1Exception {

    protected AC2Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected AC2Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
