package com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.code_name_c1.common_name2.common_name3_1;

import com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.code_name_c1.common_name2.CommonName2Exception;
import com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.RootNameException;
import com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class CommonName3_1Exception extends CommonName2Exception {

    protected CommonName3_1Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected CommonName3_1Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
