package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified.error_name1.error_name2.error_name3_1;

import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified.error_name1.error_name2.ErrorName2Exception;

/**
* Autogenerated by XGen on July 2, 2015.
*/
public class ErrorName3_1Exception extends ErrorName2Exception {

    protected ErrorName3_1Exception(String message) {
        super(message);
    }
}
