package com.rodrigodev.xgen4j.test.integration.kitchen.oven.burned_food;

import com.rodrigodev.xgen4j.test.integration.kitchen.oven.OvenError;

import java.lang.String;

import com.rodrigodev.xgen4j.test.integration.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public abstract class BurnedFoodError extends OvenError {

    public static final ErrorCode CODE = new ErrorCode("burned-food", OvenError.CODE);

    private static String MESSAGE_FORMAT = "Damn, the %s just burned! We better order some pizza.";

    private static String createMessage(String model) {
        if(model == null) throw new NullPointerException("model");

        return String.format(MESSAGE_FORMAT, model);
    }

    public static void throwException(String model) {
        throw new BurnedFoodException(CODE, createMessage(model));
    }

    public static void throwException(String model, Throwable cause) {
        throw new BurnedFoodException(CODE, createMessage(model), cause);
    }


}
