package com.rodrigodev.xgen.test.organization.packages._basePackagePartsCanBeginWithLetterOrUnderscore;




/**
 * Autogenerated by XGen on July 12, 2015.
 */
public class RootException extends RuntimeException {


    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract RootException createException(String message);

        protected abstract RootException createException(String message, Throwable cause);
    }

    protected RootException(String message) {
        super(message);
    }

    protected RootException(String message, Throwable cause) {
        super(message, cause);
    }
}
