package com.rodrigodev.xgen4j.test.message.descriptionWithCustomObjectThatGeneratesTheMessageCanBeUsed.c1.c2;

import com.rodrigodev.xgen4j.test.message.descriptionWithCustomObjectThatGeneratesTheMessageCanBeUsed.c1.C1Exception;
import com.rodrigodev.xgen4j.test.message.descriptionWithCustomObjectThatGeneratesTheMessageCanBeUsed.RootException;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class C2Exception extends C1Exception {



    protected C2Exception(String message) {
        super(message);
    }

    protected C2Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
