package com.rodrigodev.xgen.test.integration.bedroom.bed.bugs_infestation;

import com.rodrigodev.xgen.test.integration.bedroom.bed.BedException;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class BugsInfestationException extends BedException {

    protected BugsInfestationException(String message) {
        super(message);
    }
}
