package com.rodrigodev.xgen.test.integration.bedroom.bed.bugs_infestation;

import com.rodrigodev.xgen.test.integration.bedroom.bed.BedError;

/**
* Autogenerated by XGen on 12/05/15.
*/
public abstract class BugsInfestationError extends BedError {

    private static String MESSAGE_FORMAT = "Oh shoot, there is bug infestation here. We better move to %s.";

    public static void throwException(String place) {
        throw new BugsInfestationException(String.format(MESSAGE_FORMAT, place));
    }
}
