package com.rodrigodev.xgen.test.code.errorCodeEqualityIsBasedOnId_onlyName.ac1.ac2;

import com.rodrigodev.xgen.test.code.errorCodeEqualityIsBasedOnId_onlyName.ac1.AC1Error;


import com.rodrigodev.xgen.test.code.errorCodeEqualityIsBasedOnId_onlyName.ErrorCode;
import com.rodrigodev.xgen.test.code.errorCodeEqualityIsBasedOnId_onlyName.ARootException.ExceptionType;

/**
 * Autogenerated by XGen on July 11, 2015.
 */
public abstract class AC2Error extends AC1Error {

    public static final ErrorCode CODE = new ErrorCode("c2", AC1Error.CODE);


}
