package com.rodrigodev.xgen.test.generation_options.customOptionalClassIsUsedWhenCorrespondingOptionIsSet.custom_c1;

import com.rodrigodev.xgen.test.generation_options.customOptionalClassIsUsedWhenCorrespondingOptionIsSet.CustomRootError;


import com.rodrigodev.xgen.test.generation_options.customOptionalClassIsUsedWhenCorrespondingOptionIsSet.ErrorCode;
import com.rodrigodev.xgen.test.generation_options.customOptionalClassIsUsedWhenCorrespondingOptionIsSet.CustomRootException;
import com.rodrigodev.xgen.test.generation_options.customOptionalClassIsUsedWhenCorrespondingOptionIsSet.CustomRootException.ExceptionType;

/**
 * Autogenerated by XGen on July 13, 2015.
 */
public abstract class CustomC1Error extends CustomRootError {

    public static final ErrorCode CODE = new ErrorCode("custom-c-1", CustomRootError.CODE);


}
