package com.rodrigodev.xgen.test.generation_options.customOptionalClassIsUsedWhenCorrespondingOptionIsSet.custom_c1;

import com.rodrigodev.xgen.test.generation_options.customOptionalClassIsUsedWhenCorrespondingOptionIsSet.CustomRootException;
import com.rodrigodev.xgen.test.generation_options.customOptionalClassIsUsedWhenCorrespondingOptionIsSet.CustomRootException;

/**
 * Autogenerated by XGen on July 13, 2015.
 */
public class CustomC1Exception extends CustomRootException {



    protected CustomC1Exception(String message) {
        super(message);
    }

    protected CustomC1Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
