package com.rodrigodev.xgen4j.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet;




/**
 * Autogenerated by XGen on January 1, 0001.
 */
public class DefaultRootException extends RuntimeException {


    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract DefaultRootException createException(String message);

        protected abstract DefaultRootException createException(String message, Throwable cause);
    }

    protected DefaultRootException(String message) {
        super(message);
    }

    protected DefaultRootException(String message, Throwable cause) {
        super(message, cause);
    }
}
