package com.rodrigodev.xgen.test.message.descriptionWithMultipleParametersIsAllowed.e1.e2.e3;

import com.rodrigodev.xgen.test.message.descriptionWithMultipleParametersIsAllowed.e1.e2.E2Exception;

/**
* Autogenerated by XGen on July 3, 2015.
*/
public class E3Exception extends E2Exception {

    protected E3Exception(String message) {
        super(message);
    }
}
