package com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNumericId.cname1;

import com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNumericId.RootNameException;
import com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNumericId.RootNameException;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class CName1Exception extends RootNameException {



    protected CName1Exception(String message) {
        super(message);
    }

    protected CName1Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
