package com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.common_name1;

import com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.RootNameError;
import com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.ErrorCode;


/**
* Autogenerated by XGen on July 3, 2015.
*/
public abstract class CommonName1Error extends RootNameError {

    public static final ErrorCode CODE = new ErrorCode("common-name-1", RootNameError.CODE);

}
