package com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNumericId.ename1.ename2.ename3_1;

import com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNumericId.ename1.ename2.EName2Error;


import com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNumericId.ErrorCode;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public abstract class EName3_1Error extends EName2Error {

    public static final ErrorCode CODE = new ErrorCode("error-code-name-3-1", 9, EName2Error.CODE);

    private static String MESSAGE_FORMAT = "Message for EName3_1 error.";

    private static String createMessage() {

        return String.format(MESSAGE_FORMAT);
    }

    public static void throwException() {
        throw new EName3_1Exception(createMessage());
    }

    public static void throwException(Throwable cause) {
        throw new EName3_1Exception(createMessage(), cause);
    }


}
