package com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsNotSet;




/**
 * Autogenerated by XGen on July 12, 2015.
 */
public class URootException extends RuntimeException {


    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract URootException createException(String message);

        protected abstract URootException createException(String message, Throwable cause);
    }

    protected URootException(String message) {
        super(message);
    }

    protected URootException(String message, Throwable cause) {
        super(message, cause);
    }
}
