package com.rodrigodev.xgen4j.test.integration.common.appliance;

import com.rodrigodev.xgen4j.test.integration.common.CommonException;
import com.rodrigodev.xgen4j.test.integration.HouseException;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public class ApplianceException extends CommonException {



    protected ApplianceException(String message) {
        super(message);
    }

    protected ApplianceException(String message, Throwable cause) {
        super(message, cause);
    }
}
