package com.rodrigodev.xgen.test.integration.common.room.dirty;

import com.rodrigodev.xgen.test.integration.common.room.RoomException;

/**
* Autogenerated by XGen on June 29, 2015.
*/
public class DirtyException extends RoomException {

    protected DirtyException(String message) {
        super(message);
    }
}
