package com.rodrigodev.xgen.test.integration.common.room.dirty;

import com.rodrigodev.xgen.test.integration.common.room.RoomException;
import com.rodrigodev.xgen.test.integration.HouseException;

/**
* Autogenerated by XGen on July 6, 2015.
*/
public class DirtyException extends RoomException {


    protected DirtyException(String message) {
        super(message);
    }
}
