package com.rodrigodev.xgen4j.test.code.codeNumericIdAndNumberAreGeneratedWhenNameIsAlsoSpecifiedSpecified.e1.e2;

import com.rodrigodev.xgen4j.test.code.codeNumericIdAndNumberAreGeneratedWhenNameIsAlsoSpecifiedSpecified.e1.E1Error;


import com.rodrigodev.xgen4j.test.code.codeNumericIdAndNumberAreGeneratedWhenNameIsAlsoSpecifiedSpecified.ErrorCode;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public abstract class E2Error extends E1Error {

    public static final ErrorCode CODE = new ErrorCode("code-name-3", 345, E1Error.CODE);


}
