package com.rodrigodev.xgen.test.message.generatedThrowExceptionMethodChecksParamsAreNoNull.e1;

import com.rodrigodev.xgen.test.message.generatedThrowExceptionMethodChecksParamsAreNoNull.RootError;


import com.rodrigodev.xgen.test.message.generatedThrowExceptionMethodChecksParamsAreNoNull.ErrorCode;

/**
* Autogenerated by XGen on July 4, 2015.
*/
public abstract class E1Error extends RootError {

    public static final ErrorCode CODE = new ErrorCode("e-1", RootError.CODE);


}
