package com.rodrigodev.xgen4j.test.throwing.c1;

import com.rodrigodev.xgen4j.test.throwing.RootError;


import com.rodrigodev.xgen4j.test.throwing.ErrorCode;
import com.rodrigodev.xgen4j.test.throwing.RootException;
import com.rodrigodev.xgen4j.test.throwing.RootException.ExceptionType;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public abstract class C1Error extends RootError {

    public static final ErrorCode CODE = new ErrorCode("c-1", RootError.CODE);


}
