package com.rodrigodev.xgen.test.code.codeNameIsGenerated.e1.e2;

import com.rodrigodev.xgen.test.code.codeNameIsGenerated.e1.E1Exception;

/**
* Autogenerated by XGen on June 30, 2015.
*/
public class E2Exception extends E1Exception {

    protected E2Exception(String message) {
        super(message);
    }
}
