package com.rodrigodev.xgen.test.organization.hierarchy.e1;

import com.rodrigodev.xgen.test.organization.hierarchy.RootError;


import com.rodrigodev.xgen.test.organization.hierarchy.ErrorCode;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public abstract class E1Error extends RootError {

    public static final ErrorCode CODE = new ErrorCode("e-1", RootError.CODE);


}
