package com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract.e1;

import com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract.RootException;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class E1Exception extends RootException {

    protected E1Exception(String message) {
        super(message);
    }
}
