package com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified_specialCases;


import com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified_specialCases.ErrorCode;


/**
* Autogenerated by XGen on June 30, 2015.
*/
public abstract class Root_Name2Error {

    public static final ErrorCode CODE = new ErrorCode("root-name-2");

}
