package com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified_specialCases;


import com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified_specialCases.ErrorCode;


/**
* Autogenerated by XGen on June 30, 2015.
*/
public abstract class RootName9__Error {

    public static final ErrorCode CODE = new ErrorCode("root-name-9");

}
