package com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified_specialCases;



/**
* Autogenerated by XGen on June 29, 2015.
*/
public class Root_Name1Exception extends RuntimeException {

    protected Root_Name1Exception(String message) {
        super(message);
    }
}
