package com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified_specialCases;



/**
* Autogenerated by XGen on June 29, 2015.
*/
public class Root___Name5Exception extends RuntimeException {

    protected Root___Name5Exception(String message) {
        super(message);
    }
}
