package com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified_specialCases;



/**
* Autogenerated by XGen on June 29, 2015.
*/
public class Root_name11Exception extends RuntimeException {

    protected Root_name11Exception(String message) {
        super(message);
    }
}
