package com.rodrigodev.xgen4j.test.integration;



/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class HouseException extends RuntimeException {

    final private ErrorCode errorCode;

    protected HouseException(ErrorCode errorCode, String message) {
        super(message);
        this.errorCode = errorCode;
    }

    protected HouseException(ErrorCode errorCode, String message, Throwable cause) {
        super(message, cause);
        this.errorCode = errorCode;
    }

    public ErrorCode errorCode() {
        return errorCode;
    }

    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract HouseException createException(ErrorCode errorCode, String message);

        protected abstract HouseException createException(ErrorCode errorCode, String message, Throwable cause);
    }
}
