package com.rodrigodev.xgen4j.test.organization.hierarchy.c1.c2.c3_2;

import com.rodrigodev.xgen4j.test.organization.hierarchy.c1.c2.C2Exception;
import com.rodrigodev.xgen4j.test.organization.hierarchy.RootException;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public class C3_2Exception extends C2Exception {



    protected C3_2Exception(String message) {
        super(message);
    }

    protected C3_2Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
