package com.rodrigodev.xgen.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet.default_c1.default_c2;

import com.rodrigodev.xgen.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet.default_c1.DefaultC1Exception;
import com.rodrigodev.xgen.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet.DefaultRootException;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public class DefaultC2Exception extends DefaultC1Exception {



    protected DefaultC2Exception(String message) {
        super(message);
    }

    protected DefaultC2Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
