package com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.common9_name1.common9_name2.common9_name3_2;

import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.common9_name1.common9_name2.Common9Name2Exception;
import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.Root9NameException;
import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class Common9Name3_2Exception extends Common9Name2Exception {

    protected Common9Name3_2Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected Common9Name3_2Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
