package com.rodrigodev.xgen4j.test.naming.ifErrorNameHasHyphensTheyAreConvertedToUnderscores;




/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class Root__Name4__Exception extends RuntimeException {


    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract Root__Name4__Exception createException(String message);

        protected abstract Root__Name4__Exception createException(String message, Throwable cause);
    }

    protected Root__Name4__Exception(String message) {
        super(message);
    }

    protected Root__Name4__Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
