package com.rodrigodev.xgen.test.integration.kitchen.fridge;

import com.rodrigodev.xgen.test.integration.kitchen.KitchenException;

/**
* Autogenerated by XGen on July 1, 2015.
*/
public class FridgeException extends KitchenException {

    protected FridgeException(String message) {
        super(message);
    }
}
