package com.rodrigodev.xgen.test.integration.bedroom.alarm_clock.did_not_sound;

import com.rodrigodev.xgen.test.integration.bedroom.alarm_clock.AlarmClockException;

/**
* Autogenerated by XGen on June 28, 2015.
*/
public class DidNotSoundException extends AlarmClockException {

    protected DidNotSoundException(String message) {
        super(message);
    }
}
