package com.rodrigodev.xgen.test.integration.bedroom.alarm_clock.did_not_sound;

import com.rodrigodev.xgen.test.integration.bedroom.alarm_clock.AlarmClockException;
import com.rodrigodev.xgen.test.integration.HouseException;

/**
* Autogenerated by XGen on July 6, 2015.
*/
public class DidNotSoundException extends AlarmClockException {

    public static final ExceptionType TYPE = new ExceptionType();

    private static class ExceptionType extends HouseException.ExceptionType {

        @Override
        protected HouseException createException(String message) {
            return new DidNotSoundException(message);
        }
    }

    protected DidNotSoundException(String message) {
        super(message);
    }
}
