package com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.code_name_c1.common_name2;

import com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.code_name_c1.C1Exception;
import com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.RootNameException;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class CommonName2Exception extends C1Exception {



    protected CommonName2Exception(String message) {
        super(message);
    }

    protected CommonName2Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
