package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedWhenSpecified.c1.c2.c3_3;

import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedWhenSpecified.c1.c2.C2Exception;

/**
* Autogenerated by XGen on July 2, 2015.
*/
public class C3_3Exception extends C2Exception {

    protected C3_3Exception(String message) {
        super(message);
    }
}
