package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedWhenSpecified.c1.c2.c3_3;

import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedWhenSpecified.c1.c2.C2Error;
import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedWhenSpecified.ErrorCode;


/**
* Autogenerated by XGen on July 3, 2015.
*/
public abstract class C3_3Error extends C2Error {

    public static final ErrorCode CODE = new ErrorCode("code-name-c3-3", C2Error.CODE);

    private static String MESSAGE_FORMAT = "ABCDE";

    public static void throwException() {

        throw new C3_3Exception(String.format(MESSAGE_FORMAT));
    }
}
