package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.c1.common_name2.c3_2;

import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.c1.common_name2.CommonName2Error;
import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.ErrorCode;


/**
* Autogenerated by XGen on July 1, 2015.
*/
public abstract class C3_2Error extends CommonName2Error {

    public static final ErrorCode CODE = new ErrorCode("code-name-c3-2", CommonName2Error.CODE);

    private static String MESSAGE_FORMAT = "ABCDE";

    public static void throwException() {
        throw new C3_2Exception(String.format(MESSAGE_FORMAT));
    }
}
