package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.c1.common_name2.c3_2;

import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.c1.common_name2.CommonName2Exception;
import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.RootNameException;

/**
* Autogenerated by XGen on July 6, 2015.
*/
public class C3_2Exception extends CommonName2Exception {


    protected C3_2Exception(String message) {
        super(message);
    }
}
