package com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_withNumber.c1.c2;

import com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_withNumber.c1.BC1Exception;
import com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_withNumber.BRootException;
import com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_withNumber.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class BC2Exception extends BC1Exception {

    protected BC2Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected BC2Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
