package com.rodrigodev.xgen.test.integration.bedroom;

import com.rodrigodev.xgen.test.integration.HouseException;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class BedroomException extends HouseException {

    protected BedroomException(String message) {
        super(message);
    }
}
