package com.rodrigodev.xgen.test.integration.kitchen.fridge.food_not_found;

import com.rodrigodev.xgen.test.integration.kitchen.fridge.FridgeException;
import com.rodrigodev.xgen.test.integration.HouseException;

/**
* Autogenerated by XGen on July 8, 2015.
*/
public class FoodNotFoundException extends FridgeException {

    public static final ExceptionType TYPE = new ExceptionType();

    private static class ExceptionType extends HouseException.ExceptionType {

        @Override
        protected HouseException createException(String message) {
            return new FoodNotFoundException(message);
        }

        @Override
        protected HouseException createException(String message, Throwable cause) {
            return new FoodNotFoundException(message, cause);
        }
    }

    protected FoodNotFoundException(String message) {
        super(message);
    }

    protected FoodNotFoundException(String message, Throwable cause) {
        super(message, cause);
    }
}
