package com.rodrigodev.xgen.test.integration.kitchen.fridge.food_not_found;

import com.rodrigodev.xgen.test.integration.kitchen.fridge.FridgeException;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class FoodNotFoundException extends FridgeException {

    protected FoodNotFoundException(String message) {
        super(message);
    }
}
