package com.rodrigodev.xgen4j.test.generation_options.guavaOptionalClassIsUsedWhenCorrespondingOptionIsSet.c1.c2;

import com.rodrigodev.xgen4j.test.generation_options.guavaOptionalClassIsUsedWhenCorrespondingOptionIsSet.c1.C1Exception;
import com.rodrigodev.xgen4j.test.generation_options.guavaOptionalClassIsUsedWhenCorrespondingOptionIsSet.RootException;
import com.rodrigodev.xgen4j.test.generation_options.guavaOptionalClassIsUsedWhenCorrespondingOptionIsSet.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class C2Exception extends C1Exception {

    protected C2Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected C2Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
