package com.rodrigodev.xgen.test.integration.bedroom.bed.bed_is_warm;

import com.rodrigodev.xgen.test.integration.bedroom.bed.BedException;

/**
* Autogenerated by XGen on July 3, 2015.
*/
public class BedIsWarmException extends BedException {

    protected BedIsWarmException(String message) {
        super(message);
    }
}
