package com.rodrigodev.xgen4j.test.instantiation.errorWithNoDescriptionAreAbstract.c1.c2;

import com.rodrigodev.xgen4j.test.instantiation.errorWithNoDescriptionAreAbstract.c1.C1Error;


import com.rodrigodev.xgen4j.test.instantiation.errorWithNoDescriptionAreAbstract.ErrorCode;
import com.rodrigodev.xgen4j.test.instantiation.errorWithNoDescriptionAreAbstract.RootException;
import com.rodrigodev.xgen4j.test.instantiation.errorWithNoDescriptionAreAbstract.RootException.ExceptionType;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public abstract class C2Error extends C1Error {

    public static final ErrorCode CODE = new ErrorCode("c-2", C1Error.CODE);


}
