package com.rodrigodev.xgen.test.organization.packages.basePackagePartsCanContainLettersNumbersOrUnderscores1;


import com.rodrigodev.xgen.test.organization.packages.basePackagePartsCanContainLettersNumbersOrUnderscores1.ErrorCode;


/**
* Autogenerated by XGen on June 30, 2015.
*/
public abstract class RootError {

    public static final ErrorCode CODE = new ErrorCode("root");

}
