package com.rodrigodev.xgen.test.integration.kitchen.oven.too_much_smoke;

import com.rodrigodev.xgen.test.integration.kitchen.oven.OvenException;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class TooMuchSmokeException extends OvenException {

    protected TooMuchSmokeException(String message) {
        super(message);
    }
}
