package com.rodrigodev.xgen.test.organization.packages.basePackagePartsCanContain_LettersNumbersOrUnderscores_;


import com.rodrigodev.xgen.test.organization.packages.basePackagePartsCanContain_LettersNumbersOrUnderscores_.ErrorCode;


/**
* Autogenerated by XGen on July 3, 2015.
*/
public abstract class RootError {

    public static final ErrorCode CODE = new ErrorCode("root");

}
