package com.rodrigodev.xgen.test.organization.packages.basePackagePartsCanContain_LettersNumbersOrUnderscores_;




/**
* Autogenerated by XGen on July 6, 2015.
*/
public class RootException extends RuntimeException {

    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract RootException createException(String message);
    }

    protected RootException(String message) {
        super(message);
    }
}
