package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation;



/**
* Autogenerated by XGen on July 2, 2015.
*/
public class RootNameException extends RuntimeException {

    protected RootNameException(String message) {
        super(message);
    }
}
