package com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.common9_name1;

import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.Root9NameException;
import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.Root9NameException;
import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class Common9Name1Exception extends Root9NameException {

    protected Common9Name1Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected Common9Name1Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
