package com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_onlyName.c1.c2.c3_1;

import com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_onlyName.c1.c2.AC2Exception;
import com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_onlyName.ARootException;
import com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_onlyName.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class AC3_1Exception extends AC2Exception {

    protected AC3_1Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected AC3_1Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
