package com.rodrigodev.xgen.test.generation_options.java8OptionalClassIsUsedWhenCorrespondingOptionIsSet;




/**
 * Autogenerated by XGen on January 1, 0001.
 */
public class Java8RootException extends RuntimeException {


    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract Java8RootException createException(String message);

        protected abstract Java8RootException createException(String message, Throwable cause);
    }

    protected Java8RootException(String message) {
        super(message);
    }

    protected Java8RootException(String message, Throwable cause) {
        super(message, cause);
    }
}
