package com.rodrigodev.xgen.test.integration.common.appliance.scratches;

import com.rodrigodev.xgen.test.integration.common.appliance.ApplianceException;

/**
* Autogenerated by XGen on June 29, 2015.
*/
public class ScratchesException extends ApplianceException {

    protected ScratchesException(String message) {
        super(message);
    }
}
