package com.rodrigodev.xgen.test.integration.common.appliance.scratches;

import com.rodrigodev.xgen.test.integration.common.appliance.ApplianceException;
import com.rodrigodev.xgen.test.integration.HouseException;

/**
* Autogenerated by XGen on July 8, 2015.
*/
public class ScratchesException extends ApplianceException {


    protected ScratchesException(String message) {
        super(message);
    }
}
