package com.rodrigodev.xgen.test.code.codeIdIsGeneratedFromErrorNameWhenNotSpecified_mixedCase.e1.error_name2;

import com.rodrigodev.xgen.test.code.codeIdIsGeneratedFromErrorNameWhenNotSpecified_mixedCase.e1.E1Error;
import com.rodrigodev.xgen.test.code.codeIdIsGeneratedFromErrorNameWhenNotSpecified_mixedCase.ErrorCode;


/**
* Autogenerated by XGen on July 1, 2015.
*/
public abstract class ErrorName2Error extends E1Error {

    public static final ErrorCode CODE = new ErrorCode("root-name.code-name-e1.error-name-2");

}
