package com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified.error_name1.error_name2;

import com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified.error_name1.ErrorName1Error;
import com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified.ErrorCode;


/**
* Autogenerated by XGen on June 30, 2015.
*/
public abstract class ErrorName2Error extends ErrorName1Error {

    public static final ErrorCode CODE = new ErrorCode("root-name.error-name-1.error-name-2");

}
