package com.rodrigodev.xgen.test.integration.kitchen;

import com.rodrigodev.xgen.test.integration.HouseError;
import com.rodrigodev.xgen.test.integration.ErrorCode;


/**
* Autogenerated by XGen on June 28, 2015.
*/
public abstract class KitchenError extends HouseError {

    public static final ErrorCode CODE = new ErrorCode("undefined");

}
