package com.rodrigodev.xgen.test.integration.kitchen;

import com.rodrigodev.xgen.test.integration.HouseException;

/**
* Autogenerated by XGen on June 30, 2015.
*/
public class KitchenException extends HouseException {

    protected KitchenException(String message) {
        super(message);
    }
}
