package com.rodrigodev.xgen4j.test.message.descriptionWithNoParamsIsAllowed.c1.c2;

import com.rodrigodev.xgen4j.test.message.descriptionWithNoParamsIsAllowed.c1.C1Error;


import com.rodrigodev.xgen4j.test.message.descriptionWithNoParamsIsAllowed.ErrorCode;
import com.rodrigodev.xgen4j.test.message.descriptionWithNoParamsIsAllowed.RootException;
import com.rodrigodev.xgen4j.test.message.descriptionWithNoParamsIsAllowed.RootException.ExceptionType;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public abstract class C2Error extends C1Error {

    public static final ErrorCode CODE = new ErrorCode("c-2", C1Error.CODE);


}
