package com.rodrigodev.xgen.test.integration.kitchen.oven;

import com.rodrigodev.xgen.test.integration.kitchen.KitchenError;

import java.lang.String;

import com.rodrigodev.xgen.test.integration.ErrorCode;

/**
* Autogenerated by XGen on July 4, 2015.
*/
public abstract class OvenError extends KitchenError {

    public static final ErrorCode CODE = new ErrorCode("oven", KitchenError.CODE);

    private static String MESSAGE_FORMAT = "The oven is not working. Model: %s";

    private static String createMessage(String model) {
        return String.format(MESSAGE_FORMAT, model);
    }

    public static void throwException(String model) {
        if(model == null) throw new NullPointerException("model");

        throw new OvenException(createMessage(model));
    }


}
