package com.rodrigodev.xgen.test.integration.kitchen.oven;

import com.rodrigodev.xgen.test.integration.kitchen.KitchenException;

/**
* Autogenerated by XGen on June 28, 2015.
*/
public class OvenException extends KitchenException {

    protected OvenException(String message) {
        super(message);
    }
}
