package com.rodrigodev.xgen.test.integration.kitchen.oven;

import com.rodrigodev.xgen.test.integration.kitchen.KitchenError;

/**
* Autogenerated by XGen on 12/05/15.
*/
public abstract class OvenError extends KitchenError {

    private static String MESSAGE_FORMAT = "The oven is not working. Model: %s";

    public static void throwException(String model) {
        throw new OvenException(String.format(MESSAGE_FORMAT, model));
    }
}
