package com.rodrigodev.xgen.test.organization.packages.BasePackagePartsCanBeginWithLetterOrUnderscore;


import com.rodrigodev.xgen.test.organization.packages.BasePackagePartsCanBeginWithLetterOrUnderscore.ErrorCode;


/**
* Autogenerated by XGen on June 29, 2015.
*/
public abstract class RootNameError {

    public static final ErrorCode CODE = new ErrorCode("root-name");

}
