package com.rodrigodev.xgen.test.organization.packages.BasePackagePartsCanBeginWithLetterOrUnderscore;



/**
* Autogenerated by XGen on June 30, 2015.
*/
public class RootException extends RuntimeException {

    protected RootException(String message) {
        super(message);
    }
}
