package com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract;

/**
* Autogenerated by XGen on 12/05/15.
*/
public abstract class E3Error extends E2Error {

    private static String MESSAGE_FORMAT = "ABCDE";

    public static void throwException() {
        throw new E3Exception(String.format(MESSAGE_FORMAT));
    }
}
