package com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class E3Exception extends E2Exception {

    protected E3Exception(String message) {
        super(message);
    }
}
