package com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract;



/**
* Autogenerated by XGen on 25/05/15.
*/
public class RootException extends RuntimeException {

    protected RootException(String message) {
        super(message);
    }
}
