package com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract;



/**
* Autogenerated by XGen on June 28, 2015.
*/
public class RootException extends RuntimeException {

    protected RootException(String message) {
        super(message);
    }
}
