package com.rodrigodev.xgen4j.test.integration.common.appliance.damaged;

import com.rodrigodev.xgen4j.test.integration.common.appliance.ApplianceException;
import com.rodrigodev.xgen4j.test.integration.HouseException;
import com.rodrigodev.xgen4j.test.integration.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class DamagedException extends ApplianceException {

    protected DamagedException(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected DamagedException(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
