package com.rodrigodev.xgen4j.test.integration.common.appliance.damaged;

import com.rodrigodev.xgen4j.test.integration.common.appliance.ApplianceException;
import com.rodrigodev.xgen4j.test.integration.HouseException;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class DamagedException extends ApplianceException {



    protected DamagedException(String message) {
        super(message);
    }

    protected DamagedException(String message, Throwable cause) {
        super(message, cause);
    }
}
