package com.rodrigodev.xgen.test.organization.packages.error_name1.error_name2.error_name3_2;

import com.rodrigodev.xgen.test.organization.packages.error_name1.error_name2.ErrorName2Error;

/**
* Autogenerated by XGen on 12/05/15.
*/
public abstract class ErrorName3_2Error extends ErrorName2Error {

    private static String MESSAGE_FORMAT = "ABCDE";

    public static void throwException() {
        throw new ErrorName3_2Exception(String.format(MESSAGE_FORMAT));
    }
}
