package com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames_specialCases.error_name1;

import com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames_specialCases.RootNameException;

/**
* Autogenerated by XGen on June 30, 2015.
*/
public class ErrorName1Exception extends RootNameException {

    protected ErrorName1Exception(String message) {
        super(message);
    }
}
