package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.c1;

import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.RootNameError;


import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.ErrorCode;
import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.RootNameException.ExceptionType;

/**
* Autogenerated by XGen on July 8, 2015.
*/
public abstract class C1Error extends RootNameError {

    public static final ErrorCode CODE = new ErrorCode("code-name-c1", RootNameError.CODE);


}
