package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.c1;

import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.RootNameException;

/**
* Autogenerated by XGen on July 1, 2015.
*/
public class C1Exception extends RootNameException {

    protected C1Exception(String message) {
        super(message);
    }
}
