package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.c1;

import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.RootNameException;
import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedOnAMixedSituation.RootNameException;

/**
 * Autogenerated by XGen on July 12, 2015.
 */
public class C1Exception extends RootNameException {



    protected C1Exception(String message) {
        super(message);
    }

    protected C1Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
