package com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed.c1.c2;

import com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed.c1.C1Exception;
import com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed.RootException;

/**
* Autogenerated by XGen on July 8, 2015.
*/
public class C2Exception extends C1Exception {


    protected C2Exception(String message) {
        super(message);
    }

    protected C2Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
