package com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNumericId.cname1.cname2;

import com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNumericId.cname1.CName1Exception;
import com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNumericId.RootNameException;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class CName2Exception extends CName1Exception {



    protected CName2Exception(String message) {
        super(message);
    }

    protected CName2Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
