package com.rodrigodev.xgen.test.code.codeIdIsGeneratedFromErrorNameWhenNotSpecified.error_name1.error_name2.error_name3_2;

import com.rodrigodev.xgen.test.code.codeIdIsGeneratedFromErrorNameWhenNotSpecified.error_name1.error_name2.ErrorName2Error;
import com.rodrigodev.xgen.test.code.codeIdIsGeneratedFromErrorNameWhenNotSpecified.ErrorCode;


/**
* Autogenerated by XGen on July 1, 2015.
*/
public abstract class ErrorName3_2Error extends ErrorName2Error {

    public static final ErrorCode CODE = new ErrorCode("root-name.error-name-1.error-name-2.error-name-3-2");

    private static String MESSAGE_FORMAT = "ABCDE";

    public static void throwException() {
        throw new ErrorName3_2Exception(String.format(MESSAGE_FORMAT));
    }
}
