package com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_withNumber.c1;

import com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_withNumber.BRootException;
import com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_withNumber.BRootException;
import com.rodrigodev.xgen4j.test.code.errorCodeEqualityIsBasedOnId_withNumber.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class BC1Exception extends BRootException {

    protected BC1Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected BC1Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
