package com.rodrigodev.xgen4j.test.code.codeNameCanBeEqualToRootCodeNameForErrorsThatAreNotChildrenOfRootError_nameOnly.code_name_c1;

import com.rodrigodev.xgen4j.test.code.codeNameCanBeEqualToRootCodeNameForErrorsThatAreNotChildrenOfRootError_nameOnly.RootException;
import com.rodrigodev.xgen4j.test.code.codeNameCanBeEqualToRootCodeNameForErrorsThatAreNotChildrenOfRootError_nameOnly.RootException;
import com.rodrigodev.xgen4j.test.code.codeNameCanBeEqualToRootCodeNameForErrorsThatAreNotChildrenOfRootError_nameOnly.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class C1Exception extends RootException {

    protected C1Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected C1Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
