package com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed.e1.e2;

import com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed.e1.E1Error;

/**
* Autogenerated by XGen on 12/05/15.
*/
public abstract class E2Error extends E1Error {

}
