package com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsSetAsFalse.u2c1;

import com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsSetAsFalse.U2RootException;
import com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsSetAsFalse.U2RootException;

/**
 * Autogenerated by XGen on July 12, 2015.
 */
public class U2C1Exception extends U2RootException {



    protected U2C1Exception(String message) {
        super(message);
    }

    protected U2C1Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
