package com.rodrigodev.xgen4j.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet.default_c1;

import com.rodrigodev.xgen4j.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet.DefaultRootException;
import com.rodrigodev.xgen4j.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet.DefaultRootException;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class DefaultC1Exception extends DefaultRootException {



    protected DefaultC1Exception(String message) {
        super(message);
    }

    protected DefaultC1Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
