package com.rodrigodev.xgen4j.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet.default_c1;

import com.rodrigodev.xgen4j.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet.DefaultRootError;


import com.rodrigodev.xgen4j.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet.ErrorCode;
import com.rodrigodev.xgen4j.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet.DefaultRootException;
import com.rodrigodev.xgen4j.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet.DefaultRootException.ExceptionType;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public abstract class DefaultC1Error extends DefaultRootError {

    public static final ErrorCode CODE = new ErrorCode("default-c-1", DefaultRootError.CODE);


}
