package com.rodrigodev.xgen4j.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsNotSet.ue1.ue2.ue3_2;

import com.rodrigodev.xgen4j.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsNotSet.ue1.ue2.UE2Exception;
import com.rodrigodev.xgen4j.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsNotSet.URootException;
import com.rodrigodev.xgen4j.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsNotSet.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class UE3_2Exception extends UE2Exception {

    public static final ExceptionType TYPE = new ExceptionType();

    protected UE3_2Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected UE3_2Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }

    private static class ExceptionType extends URootException.ExceptionType {

        @Override
        protected URootException createException(ErrorCode errorCode, String message) {
            return new UE3_2Exception(errorCode, message);
        }

        @Override
        protected URootException createException(ErrorCode errorCode, String message, Throwable cause) {
            return new UE3_2Exception(errorCode, message, cause);
        }
    }
}
