package com.rodrigodev.xgen4j.test.throwing.c1.c2.c3_3;

import com.rodrigodev.xgen4j.test.throwing.c1.c2.C2Exception;
import com.rodrigodev.xgen4j.test.throwing.RootException;
import com.rodrigodev.xgen4j.test.throwing.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class C3_3Exception extends C2Exception {

    protected C3_3Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected C3_3Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
