package com.rodrigodev.xgen.test.code.errorCodeEqualityIsBasedOnId_onlyName.ac1.ac2.ac3_1;

import com.rodrigodev.xgen.test.code.errorCodeEqualityIsBasedOnId_onlyName.ac1.ac2.AC2Exception;
import com.rodrigodev.xgen.test.code.errorCodeEqualityIsBasedOnId_onlyName.ARootException;

/**
 * Autogenerated by XGen on July 11, 2015.
 */
public class AC3_1Exception extends AC2Exception {



    protected AC3_1Exception(String message) {
        super(message);
    }

    protected AC3_1Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
