package com.rodrigodev.xgen.test.generation_options.customOptionalClassIsUsedWhenCorrespondingOptionIsSet.custom_c1.custom_c2.custom_c3_3;

import com.rodrigodev.xgen.test.generation_options.customOptionalClassIsUsedWhenCorrespondingOptionIsSet.custom_c1.custom_c2.CustomC2Exception;
import com.rodrigodev.xgen.test.generation_options.customOptionalClassIsUsedWhenCorrespondingOptionIsSet.CustomRootException;

/**
 * Autogenerated by XGen on July 13, 2015.
 */
public class CustomC3_3Exception extends CustomC2Exception {



    protected CustomC3_3Exception(String message) {
        super(message);
    }

    protected CustomC3_3Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
