package com.rodrigodev.xgen.test.integration.common.appliance.damaged;

import com.rodrigodev.xgen.test.integration.common.appliance.ApplianceException;

/**
* Autogenerated by XGen on July 3, 2015.
*/
public class DamagedException extends ApplianceException {

    protected DamagedException(String message) {
        super(message);
    }
}
