package com.rodrigodev.xgen.test.generation_options.checkedExceptionsAreGeneratedWhenCorrespondingOptionIsSet;




/**
 * Autogenerated by XGen on January 1, 0001.
 */
public class CRootException extends Exception {


    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract CRootException createException(String message);

        protected abstract CRootException createException(String message, Throwable cause);
    }

    protected CRootException(String message) {
        super(message);
    }

    protected CRootException(String message, Throwable cause) {
        super(message, cause);
    }
}
