package com.rodrigodev.xgen.test.integration.common;

import com.rodrigodev.xgen.test.integration.HouseException;

/**
* Autogenerated by XGen on June 29, 2015.
*/
public class CommonException extends HouseException {

    protected CommonException(String message) {
        super(message);
    }
}
