package com.rodrigodev.xgen.test.integration.common;

import com.rodrigodev.xgen.test.integration.HouseError;


import com.rodrigodev.xgen.test.integration.ErrorCode;
import com.rodrigodev.xgen.test.integration.HouseException.ExceptionType;

/**
 * Autogenerated by XGen on July 11, 2015.
 */
public abstract class CommonError extends HouseError {

    public static final ErrorCode CODE = new ErrorCode("common", HouseError.CODE);


}
