package com.rodrigodev.xgen.test.integration.common;

import com.rodrigodev.xgen.test.integration.HouseError;
import com.rodrigodev.xgen.test.integration.ErrorCode;


/**
* Autogenerated by XGen on June 30, 2015.
*/
public abstract class CommonError extends HouseError {

    public static final ErrorCode CODE = new ErrorCode("house.common");

}
