package com.rodrigodev.xgen4j.test.code.codeNumberCanBeEqualToRootCodeNumberForErrorsThatAreNotChildrenOfRootError.c1.c2.c3;

import com.rodrigodev.xgen4j.test.code.codeNumberCanBeEqualToRootCodeNumberForErrorsThatAreNotChildrenOfRootError.c1.c2.C2Exception;
import com.rodrigodev.xgen4j.test.code.codeNumberCanBeEqualToRootCodeNumberForErrorsThatAreNotChildrenOfRootError.RootException;
import com.rodrigodev.xgen4j.test.code.codeNumberCanBeEqualToRootCodeNumberForErrorsThatAreNotChildrenOfRootError.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class C3Exception extends C2Exception {

    protected C3Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected C3Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
