package com.rodrigodev.xgen.test.organization.packages.error_name1.error_name2;

import com.rodrigodev.xgen.test.organization.packages.error_name1.ErrorName1Exception;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class ErrorName2Exception extends ErrorName1Exception {

    protected ErrorName2Exception(String message) {
        super(message);
    }
}
