package com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed;



/**
* Autogenerated by XGen on 25/05/15.
*/
public class RootException extends RuntimeException {

    protected RootException(String message) {
        super(message);
    }
}
