package com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed;


import com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed.ErrorCode;


/**
* Autogenerated by XGen on June 29, 2015.
*/
public abstract class RootError {

    public static final ErrorCode CODE = new ErrorCode("root");

}
