package com.rodrigodev.xgen.test.code.codeNumericIdAndNumberAreGeneratedWhenNameIsAlsoSpecifiedSpecified;


import com.rodrigodev.xgen.test.code.codeNumericIdAndNumberAreGeneratedWhenNameIsAlsoSpecifiedSpecified.ErrorCode;


/**
* Autogenerated by XGen on July 2, 2015.
*/
public abstract class RootError {

    public static final ErrorCode CODE = new ErrorCode("code-name-1", 123);

}
