package com.rodrigodev.xgen.test.integration.bedroom.bed.pillow_not_found;

import com.rodrigodev.xgen.test.integration.bedroom.bed.BedException;

/**
* Autogenerated by XGen on July 1, 2015.
*/
public class PillowNotFoundException extends BedException {

    protected PillowNotFoundException(String message) {
        super(message);
    }
}
