package com.rodrigodev.xgen.test.integration.bedroom.bed.pillow_not_found;

import com.rodrigodev.xgen.test.integration.bedroom.bed.BedError;
import com.rodrigodev.xgen.test.integration.ErrorCode;

import java.lang.String;

/**
* Autogenerated by XGen on July 2, 2015.
*/
public abstract class PillowNotFoundError extends BedError {

    public static final ErrorCode CODE = new ErrorCode("pillow-not-found", BedError.CODE);

    private static String MESSAGE_FORMAT = "There is no pillow! How can %s sleep here?";

    public static void throwException(String personName) {
        throw new PillowNotFoundException(String.format(MESSAGE_FORMAT, personName));
    }
}
