package com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified.error_name1.error_name2;

import com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified.error_name1.ErrorName1Error;


import com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public abstract class ErrorName2Error extends ErrorName1Error {

    public static final ErrorCode CODE = new ErrorCode("error-name-2", ErrorName1Error.CODE);


}
