package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified_specialCases;




/**
* Autogenerated by XGen on July 4, 2015.
*/
public class Root_Name1Exception extends RuntimeException {

    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract Root_Name1Exception createException(String message);
    }

    protected Root_Name1Exception(String message) {
        super(message);
    }
}
