package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified_specialCases;




/**
* Autogenerated by XGen on July 8, 2015.
*/
public class RootName6_Exception extends RuntimeException {

    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract RootName6_Exception createException(String message);

        protected abstract RootName6_Exception createException(String message, Throwable cause);
    }

    protected RootName6_Exception(String message) {
        super(message);
    }

    protected RootName6_Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
