package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified_specialCases;


import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified_specialCases.ErrorCode;


/**
* Autogenerated by XGen on July 1, 2015.
*/
public abstract class RootName7_Error {

    public static final ErrorCode CODE = new ErrorCode("root-name-7");

}
