package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified_specialCases;



/**
* Autogenerated by XGen on July 3, 2015.
*/
public class Root__Name4Exception extends RuntimeException {

    protected Root__Name4Exception(String message) {
        super(message);
    }
}
