package com.rodrigodev.xgen4j.test.message.descriptionWithNoParamsIsAllowed.c1.c2.c3;

import com.rodrigodev.xgen4j.test.message.descriptionWithNoParamsIsAllowed.c1.c2.C2Error;


import com.rodrigodev.xgen4j.test.message.descriptionWithNoParamsIsAllowed.ErrorCode;
import com.rodrigodev.xgen4j.test.message.descriptionWithNoParamsIsAllowed.RootException;
import com.rodrigodev.xgen4j.test.message.descriptionWithNoParamsIsAllowed.RootException.ExceptionType;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public abstract class C3Error extends C2Error {

    public static final ErrorCode CODE = new ErrorCode("c-3", C2Error.CODE);

    private static String MESSAGE_FORMAT = "Some description.";

    private static String createMessage() {

        return String.format(MESSAGE_FORMAT);
    }

    public static void throwException() {
        throw new C3Exception(CODE, createMessage());
    }

    public static void throwException(Throwable cause) {
        throw new C3Exception(CODE, createMessage(), cause);
    }

    public static void throwException(ExceptionType exceptionType) {
        throwExceptionForCommonError(CODE, exceptionType, createMessage());
    }

    public static void throwException(ExceptionType exceptionType, Throwable cause) {
        throwExceptionForCommonError(CODE, exceptionType, createMessage(), cause);
    }

}
