package com.rodrigodev.xgen.test.organization.hierarchy.c1.c2.c3_3;

import com.rodrigodev.xgen.test.organization.hierarchy.c1.c2.C2Error;


/**
* Autogenerated by XGen on 12/05/15.
*/
public abstract class C3_3Error extends C2Error {

    private static String MESSAGE_FORMAT = "ABCDE";

    public static void throwException() {
        throw new C3_3Exception(String.format(MESSAGE_FORMAT));
    }
}
