package com.rodrigodev.xgen.test.integration.common.room.too_small;

import com.rodrigodev.xgen.test.integration.common.room.RoomError;
import com.rodrigodev.xgen.test.integration.ErrorCode;

import java.lang.String;

/**
* Autogenerated by XGen on June 30, 2015.
*/
public abstract class TooSmallError extends RoomError {

    public static final ErrorCode CODE = new ErrorCode("house.common.room.too-small");

    private static String MESSAGE_FORMAT = "%s is too damn small!";

    public static void throwException(String roomName) {
        throw new TooSmallException(String.format(MESSAGE_FORMAT, roomName));
    }
}
