package com.rodrigodev.xgen.test.integration.common.room.too_small;

import com.rodrigodev.xgen.test.integration.common.room.RoomException;

/**
* Autogenerated by XGen on July 2, 2015.
*/
public class TooSmallException extends RoomException {

    protected TooSmallException(String message) {
        super(message);
    }
}
