package com.rodrigodev.xgen.test.integration.common.room.too_small;

import com.rodrigodev.xgen.test.integration.common.room.RoomError;

/**
* Autogenerated by XGen on 12/05/15.
*/
public abstract class TooSmallError extends RoomError {

    private static String MESSAGE_FORMAT = "%s is too damn small!";

    public static void throwException(String roomName) {
        throw new TooSmallException(String.format(MESSAGE_FORMAT, roomName));
    }
}
