package com.rodrigodev.xgen.test.integration.common.room.too_small;

import com.rodrigodev.xgen.test.integration.common.room.RoomException;
import com.rodrigodev.xgen.test.integration.HouseException;

/**
* Autogenerated by XGen on July 4, 2015.
*/
public class TooSmallException extends RoomException {


    protected TooSmallException(String message) {
        super(message);
    }
}
