package com.rodrigodev.xgen.test.throwing.c1;

import com.rodrigodev.xgen.test.throwing.RootException;

/**
* Autogenerated by XGen on July 3, 2015.
*/
public class C1Exception extends RootException {

    protected C1Exception(String message) {
        super(message);
    }
}
