package com.rodrigodev.xgen.test.organization.hierarchy.c1;

import com.rodrigodev.xgen.test.organization.hierarchy.RootError;


import com.rodrigodev.xgen.test.organization.hierarchy.ErrorCode;
import com.rodrigodev.xgen.test.organization.hierarchy.RootException.ExceptionType;

/**
* Autogenerated by XGen on July 8, 2015.
*/
public abstract class C1Error extends RootError {

    public static final ErrorCode CODE = new ErrorCode("c-1", RootError.CODE);


}
