package com.rodrigodev.xgen.test.organization.hierarchy.c1;

import com.rodrigodev.xgen.test.organization.hierarchy.RootError;
import com.rodrigodev.xgen.test.organization.hierarchy.ErrorCode;


/**
* Autogenerated by XGen on July 1, 2015.
*/
public abstract class C1Error extends RootError {

    public static final ErrorCode CODE = new ErrorCode("root.c-1");

}
