package com.rodrigodev.xgen.test.organization.hierarchy.c1;

import com.rodrigodev.xgen.test.organization.hierarchy.RootException;

/**
* Autogenerated by XGen on June 30, 2015.
*/
public class C1Exception extends RootException {

    protected C1Exception(String message) {
        super(message);
    }
}
