package com.rodrigodev.xgen.test.message.noParamsForDescription;

/**
* Autogenerated by XGen on 12/05/15.
*/
public class E3Error extends E2Error {

    private static String MESSAGE_FORMAT = "Some description.";

    public static void throwException() {
        throw new E3Exception(String.format(MESSAGE_FORMAT));
    }
}
