package com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified_mixedCase.c1.common_name2.common_name3_3;

import com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified_mixedCase.c1.common_name2.CommonName2Exception;

/**
* Autogenerated by XGen on June 30, 2015.
*/
public class CommonName3_3Exception extends CommonName2Exception {

    protected CommonName3_3Exception(String message) {
        super(message);
    }
}
