package com.rodrigodev.xgen4j.test.integration.kitchen.fridge.food_not_found;

import com.rodrigodev.xgen4j.test.integration.kitchen.fridge.FridgeException;
import com.rodrigodev.xgen4j.test.integration.HouseException;
import com.rodrigodev.xgen4j.test.integration.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class FoodNotFoundException extends FridgeException {

    public static final ExceptionType TYPE = new ExceptionType();

    protected FoodNotFoundException(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected FoodNotFoundException(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }

    private static class ExceptionType extends HouseException.ExceptionType {

        @Override
        protected HouseException createException(ErrorCode errorCode, String message) {
            return new FoodNotFoundException(errorCode, message);
        }

        @Override
        protected HouseException createException(ErrorCode errorCode, String message, Throwable cause) {
            return new FoodNotFoundException(errorCode, message, cause);
        }
    }
}
