package com.rodrigodev.xgen.test.code.codeNameIsGenerated.e1;

import com.rodrigodev.xgen.test.code.codeNameIsGenerated.RootError;
import com.rodrigodev.xgen.test.code.codeNameIsGenerated.ErrorCode;


/**
* Autogenerated by XGen on June 29, 2015.
*/
public abstract class E1Error extends RootError {

    public static final ErrorCode CODE = new ErrorCode("code-name-root.code-name-e1");

}
