package com.rodrigodev.xgen.test.message.descriptionWithCustomObjectThatGeneratesTheMessageCanBeUsed_inheritedImplementation;


import com.rodrigodev.xgen.test.message.descriptionWithCustomObjectThatGeneratesTheMessageCanBeUsed_inheritedImplementation.ErrorCode;


/**
* Autogenerated by XGen on July 2, 2015.
*/
public abstract class RootError {

    public static final ErrorCode CODE = new ErrorCode("root");

}
