package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedWhenSpecified.c1.c2;

import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedWhenSpecified.c1.C1Error;
import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedWhenSpecified.ErrorCode;


/**
* Autogenerated by XGen on July 1, 2015.
*/
public abstract class C2Error extends C1Error {

    public static final ErrorCode CODE = new ErrorCode("code-name-c2", C1Error.CODE);

}
