package com.rodrigodev.xgen.test.info_generation.eb1.eb2.eb3_1;

import com.rodrigodev.xgen.test.info_generation.eb1.eb2.EB2Error;


import com.rodrigodev.xgen.test.info_generation.ErrorCode;

/**
 * Autogenerated by XGen on July 11, 2015.
 */
public abstract class EB3_1Error extends EB2Error {

    public static final ErrorCode CODE = new ErrorCode("e-b-3-1", EB2Error.CODE);

    private static String MESSAGE_FORMAT = "Message for EB3_1 error.";

    private static String createMessage() {

        return String.format(MESSAGE_FORMAT);
    }

    public static void throwException() {
        throw new EB3_1Exception(createMessage());
    }

    public static void throwException(Throwable cause) {
        throw new EB3_1Exception(createMessage(), cause);
    }


}
