package com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames_specialCases;




/**
* Autogenerated by XGen on July 4, 2015.
*/
public class RootNameException extends RuntimeException {

    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract RootNameException createException(String message);
    }

    protected RootNameException(String message) {
        super(message);
    }
}
