package ${packagePath};

<#if parent??>import ${parent.canonicalName};</#if>
<#if root??>import ${root.canonicalName};</#if>

/**
* Autogenerated by XGen on ${currentDate}.
*/
public class ${name} extends <#if parent??>${parent.name}<#else>RuntimeException</#if> {

    <#if root??>
    <#if !common>
    public static final ExceptionType TYPE = new ExceptionType();

    private static class ExceptionType extends ${root.name}.ExceptionType {

        @Override
        protected ${root.name} createException(String message) {
            return new ${name}(message);
        }
    }
    </#if>
    <#else>
    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract ${name} createException(String message);
    }
    </#if>

    protected ${name}(String message) {
        super(message);
    }
}
