package ${packagePath};

/**
* Autogenerated by XGen on 25/05/15.
*/
public class ${name} extends <#if parentName??>${parentName}<#else>RuntimeException</#if> {

    protected ${name}(String message) {
        super(message);
    }
}
