package com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.common_name1.common_name2;

import com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.common_name1.CommonName1Error;
import com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.ErrorCode;


/**
* Autogenerated by XGen on July 1, 2015.
*/
public abstract class CommonName2Error extends CommonName1Error {

    public static final ErrorCode CODE = new ErrorCode("common-name-2", CommonName1Error.CODE);

}
