package com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsNotSet.uc1.uc2.uc3_2;

import com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsNotSet.uc1.uc2.UC2Exception;
import com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsNotSet.URootException;

/**
 * Autogenerated by XGen on July 13, 2015.
 */
public class UC3_2Exception extends UC2Exception {



    protected UC3_2Exception(String message) {
        super(message);
    }

    protected UC3_2Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
