package com.rodrigodev.xgen.test.generation_options.guavaOptionalClassIsUsedWhenCorrespondingOptionIsSet.guava_c1;

import com.rodrigodev.xgen.test.generation_options.guavaOptionalClassIsUsedWhenCorrespondingOptionIsSet.GuavaRootException;
import com.rodrigodev.xgen.test.generation_options.guavaOptionalClassIsUsedWhenCorrespondingOptionIsSet.GuavaRootException;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public class GuavaC1Exception extends GuavaRootException {



    protected GuavaC1Exception(String message) {
        super(message);
    }

    protected GuavaC1Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
