package com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed.e1;

import com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed.RootError;
import com.rodrigodev.xgen.test.message.descriptionWithNoParamsIsAllowed.ErrorCode;


/**
* Autogenerated by XGen on July 1, 2015.
*/
public abstract class E1Error extends RootError {

    public static final ErrorCode CODE = new ErrorCode("e-1", RootError.CODE);

}
