package com.rodrigodev.xgen.test.integration.bedroom.alarm_clock.shut_up;

import com.rodrigodev.xgen.test.integration.bedroom.alarm_clock.AlarmClockException;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class ShutUpException extends AlarmClockException {

    protected ShutUpException(String message) {
        super(message);
    }
}
