package com.rodrigodev.xgen4j.test.integration.bedroom.alarm_clock.too_early;

import com.rodrigodev.xgen4j.test.integration.bedroom.alarm_clock.AlarmClockError;

import java.lang.String;

import com.rodrigodev.xgen4j.test.integration.ErrorCode;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public abstract class TooEarlyError extends AlarmClockError {

    public static final ErrorCode CODE = new ErrorCode("too-early", AlarmClockError.CODE);

    private static String MESSAGE_FORMAT = "It's just %s, still to early to wake up.";

    private static String createMessage(String time) {
        if(time == null) throw new NullPointerException("time");

        return String.format(MESSAGE_FORMAT, time);
    }

    public static void throwException(String time) {
        throw new TooEarlyException(createMessage(time));
    }

    public static void throwException(String time, Throwable cause) {
        throw new TooEarlyException(createMessage(time), cause);
    }


}
