package com.rodrigodev.xgen.test.generation_options.guavaOptionalClassIsUsedWhenCorrespondingOptionIsSet.guava_e1.guava_e2;

import com.rodrigodev.xgen.test.generation_options.guavaOptionalClassIsUsedWhenCorrespondingOptionIsSet.guava_e1.GuavaE1Error;


import com.rodrigodev.xgen.test.generation_options.guavaOptionalClassIsUsedWhenCorrespondingOptionIsSet.ErrorCode;

/**
 * Autogenerated by XGen on July 13, 2015.
 */
public abstract class GuavaE2Error extends GuavaE1Error {

    public static final ErrorCode CODE = new ErrorCode("guava-e-2", GuavaE1Error.CODE);


}
