package com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsSetAsFalse.u2e1;

import com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsSetAsFalse.U2RootError;


import com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsSetAsFalse.ErrorCode;

/**
 * Autogenerated by XGen on July 13, 2015.
 */
public abstract class U2E1Error extends U2RootError {

    public static final ErrorCode CODE = new ErrorCode("u-2-e-1", U2RootError.CODE);


}
