package com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.error9_name1;

import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.Root9NameException;
import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.Root9NameException;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class Error9Name1Exception extends Root9NameException {

    public static final ExceptionType TYPE = new ExceptionType();

    private static class ExceptionType extends Root9NameException.ExceptionType {

        @Override
        protected Root9NameException createException(String message) {
            return new Error9Name1Exception(message);
        }

        @Override
        protected Root9NameException createException(String message, Throwable cause) {
            return new Error9Name1Exception(message, cause);
        }
    }

    protected Error9Name1Exception(String message) {
        super(message);
    }

    protected Error9Name1Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
