package com.rodrigodev.xgen4j.test.integration.common;

import com.rodrigodev.xgen4j.test.integration.HouseException;
import com.rodrigodev.xgen4j.test.integration.HouseException;
import com.rodrigodev.xgen4j.test.integration.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class CommonException extends HouseException {

    protected CommonException(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected CommonException(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
