package com.rodrigodev.xgen4j.test.integration.common;

import com.rodrigodev.xgen4j.test.integration.HouseError;


import com.rodrigodev.xgen4j.test.integration.ErrorCode;
import com.rodrigodev.xgen4j.test.integration.HouseException;
import com.rodrigodev.xgen4j.test.integration.HouseException.ExceptionType;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public abstract class CommonError extends HouseError {

    public static final ErrorCode CODE = new ErrorCode("common", HouseError.CODE);


}
