package com.rodrigodev.xgen.test.message.descriptionWithMultipleParametersIsAllowed.c1.c2.c3;

import com.rodrigodev.xgen.test.message.descriptionWithMultipleParametersIsAllowed.c1.c2.C2Exception;
import com.rodrigodev.xgen.test.message.descriptionWithMultipleParametersIsAllowed.RootException;

/**
 * Autogenerated by XGen on July 12, 2015.
 */
public class C3Exception extends C2Exception {



    protected C3Exception(String message) {
        super(message);
    }

    protected C3Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
