package com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedWhenSpecified.code_9_name_c1.code_9_name_c2.code_9_name_c3_3;

import com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedWhenSpecified.code_9_name_c1.code_9_name_c2.C2Exception;
import com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedWhenSpecified.RootException;
import com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedWhenSpecified.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class C3_3Exception extends C2Exception {

    protected C3_3Exception(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected C3_3Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }
}
