package com.rodrigodev.xgen.test.generation_options.checkedExceptionsAreGeneratedWhenCorrespondingOptionIsSet.ce1;

import com.rodrigodev.xgen.test.generation_options.checkedExceptionsAreGeneratedWhenCorrespondingOptionIsSet.CRootError;


import com.rodrigodev.xgen.test.generation_options.checkedExceptionsAreGeneratedWhenCorrespondingOptionIsSet.ErrorCode;

/**
 * Autogenerated by XGen on July 13, 2015.
 */
public abstract class CE1Error extends CRootError {

    public static final ErrorCode CODE = new ErrorCode("c-e-1", CRootError.CODE);


}
