package com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.error_name1.error_name2;

import com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.error_name1.ErrorName1Exception;

/**
* Autogenerated by XGen on June 30, 2015.
*/
public class ErrorName2Exception extends ErrorName1Exception {

    protected ErrorName2Exception(String message) {
        super(message);
    }
}
