package com.rodrigodev.xgen.test.code.codeIdIsGeneratedFromErrorNameWhenNotSpecified_specialCases;


import com.rodrigodev.xgen.test.code.codeIdIsGeneratedFromErrorNameWhenNotSpecified_specialCases.ErrorCode;


/**
* Autogenerated by XGen on July 1, 2015.
*/
public abstract class Root_name11Error {

    public static final ErrorCode CODE = new ErrorCode("root-name-11");

}
