package com.rodrigodev.xgen.test.code.codeIdIsGeneratedFromErrorNameWhenNotSpecified_specialCases;



/**
* Autogenerated by XGen on July 1, 2015.
*/
public class RootName9__Exception extends RuntimeException {

    protected RootName9__Exception(String message) {
        super(message);
    }
}
