package com.rodrigodev.xgen.test.code.codeIdIsGeneratedFromErrorNameWhenNotSpecified_specialCases;



/**
* Autogenerated by XGen on July 1, 2015.
*/
public class Root_Name2Exception extends RuntimeException {

    protected Root_Name2Exception(String message) {
        super(message);
    }
}
