package com.rodrigodev.xgen4j.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet.c1;

import com.rodrigodev.xgen4j.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet.RootException;
import com.rodrigodev.xgen4j.test.generation_options.java8OptionalClassIsUsedWhenNoOptionIsSet.RootException;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class C1Exception extends RootException {



    protected C1Exception(String message) {
        super(message);
    }

    protected C1Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
