package com.rodrigodev.xgen.test.code.codeNameIsGenerated.c1;

import com.rodrigodev.xgen.test.code.codeNameIsGenerated.RootException;

/**
* Autogenerated by XGen on June 29, 2015.
*/
public class C1Exception extends RootException {

    protected C1Exception(String message) {
        super(message);
    }
}
