package com.rodrigodev.xgen.test.generation_options.checkedExceptionsAreGeneratedWhenCorrespondingOptionIsSet.ce1.ce2;

import com.rodrigodev.xgen.test.generation_options.checkedExceptionsAreGeneratedWhenCorrespondingOptionIsSet.ce1.CE1Error;


import com.rodrigodev.xgen.test.generation_options.checkedExceptionsAreGeneratedWhenCorrespondingOptionIsSet.ErrorCode;

/**
 * Autogenerated by XGen on July 12, 2015.
 */
public abstract class CE2Error extends CE1Error {

    public static final ErrorCode CODE = new ErrorCode("c-e-2", CE1Error.CODE);


}
