package com.rodrigodev.xgen.test.naming.errorNameCanContainLettersNumbersHyphensOrUnderscores;


import com.rodrigodev.xgen.test.naming.errorNameCanContainLettersNumbersHyphensOrUnderscores.ErrorCode;


/**
* Autogenerated by XGen on July 1, 2015.
*/
public abstract class Root1Name1Error {

    public static final ErrorCode CODE = new ErrorCode("root-1-name-1");

}
