package com.rodrigodev.xgen.test.naming.errorNameCanContainLettersNumbersHyphensOrUnderscores;



/**
* Autogenerated by XGen on July 2, 2015.
*/
public class Root_Name3_Exception extends RuntimeException {

    protected Root_Name3_Exception(String message) {
        super(message);
    }
}
