package com.rodrigodev.xgen.test.naming.errorNameCanContainLettersNumbersHyphensOrUnderscores;


import com.rodrigodev.xgen.test.naming.errorNameCanContainLettersNumbersHyphensOrUnderscores.ErrorCode;


/**
* Autogenerated by XGen on June 30, 2015.
*/
public abstract class RootName1Error {

    public static final ErrorCode CODE = new ErrorCode("root-name-1");

}
