package com.rodrigodev.xgen.test.naming.errorNameCanContainLettersNumbersHyphensOrUnderscores;



/**
* Autogenerated by XGen on July 2, 2015.
*/
public class Root1Name1Exception extends RuntimeException {

    protected Root1Name1Exception(String message) {
        super(message);
    }
}
