package com.rodrigodev.xgen.test.naming.errorNameCanContainLettersNumbersHyphensOrUnderscores;



/**
* Autogenerated by XGen on June 30, 2015.
*/
public class RootName_Exception extends RuntimeException {

    protected RootName_Exception(String message) {
        super(message);
    }
}
