package com.rodrigodev.xgen.test.naming.errorNameCanContainLettersNumbersHyphensOrUnderscores;


import com.rodrigodev.xgen.test.naming.errorNameCanContainLettersNumbersHyphensOrUnderscores.ErrorCode;


/**
* Autogenerated by XGen on July 2, 2015.
*/
public abstract class RootNameError {

    public static final ErrorCode CODE = new ErrorCode("root-name");

}
