package com.rodrigodev.xgen.test.naming.errorNameCanContainLettersNumbersHyphensOrUnderscores;




import com.rodrigodev.xgen.test.naming.errorNameCanContainLettersNumbersHyphensOrUnderscores.Root1Name1Exception.ExceptionType;

/**
* Autogenerated by XGen on July 4, 2015.
*/
public abstract class Root1Name1Error {

    public static final ErrorCode CODE = new ErrorCode("root-1-name-1");


    protected static void throwExceptionForCommonError(ExceptionType exceptionType, String message) {
        throw exceptionType.createException(message);
    }
}
