package com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract.c1;

import com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract.RootError;


/**
* Autogenerated by XGen on 12/05/15.
*/
public abstract class C1Error extends RootError {

}
