package com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract.c1;

import com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract.RootException;
import com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract.RootException;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public class C1Exception extends RootException {



    protected C1Exception(String message) {
        super(message);
    }

    protected C1Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
