package com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract.c1;

import com.rodrigodev.xgen.test.instantiation.errorWithNoDescriptionAreAbstract.RootException;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class C1Exception extends RootException {

    protected C1Exception(String message) {
        super(message);
    }
}
