package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified_specialCases;




/**
 * Autogenerated by XGen on January 1, 0001.
 */
public class Root_name12Exception extends RuntimeException {


    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract Root_name12Exception createException(String message);

        protected abstract Root_name12Exception createException(String message, Throwable cause);
    }

    protected Root_name12Exception(String message) {
        super(message);
    }

    protected Root_name12Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
