package com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified_specialCases;




/**
 * Autogenerated by XGen on January 1, 0001.
 */
public class RootName8__Exception extends RuntimeException {


    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract RootName8__Exception createException(String message);

        protected abstract RootName8__Exception createException(String message, Throwable cause);
    }

    protected RootName8__Exception(String message) {
        super(message);
    }

    protected RootName8__Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
