package com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified_specialCases;




/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class Root___Name5Exception extends RuntimeException {


    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract Root___Name5Exception createException(String message);

        protected abstract Root___Name5Exception createException(String message, Throwable cause);
    }

    protected Root___Name5Exception(String message) {
        super(message);
    }

    protected Root___Name5Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
