package com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified_specialCases;



/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class Root___Name___9___Name5Exception extends RuntimeException {

    final private ErrorCode errorCode;

    protected Root___Name___9___Name5Exception(ErrorCode errorCode, String message) {
        super(message);
        this.errorCode = errorCode;
    }

    protected Root___Name___9___Name5Exception(ErrorCode errorCode, String message, Throwable cause) {
        super(message, cause);
        this.errorCode = errorCode;
    }

    public ErrorCode errorCode() {
        return errorCode;
    }

    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract Root___Name___9___Name5Exception createException(ErrorCode errorCode, String message);

        protected abstract Root___Name___9___Name5Exception createException(ErrorCode errorCode, String message, Throwable cause);
    }
}
