package com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified_specialCases;




/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class RootName__9__Exception extends RuntimeException {


    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract RootName__9__Exception createException(String message);

        protected abstract RootName__9__Exception createException(String message, Throwable cause);
    }

    protected RootName__9__Exception(String message) {
        super(message);
    }

    protected RootName__9__Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
