package com.rodrigodev.xgen4j.test.code.codeIdAndNameAreGeneratedFromErrorNameWhenNotSpecified_specialCases;




/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class Root_name_9_name11Exception extends RuntimeException {


    public abstract static class ExceptionType {

        protected ExceptionType() {
        }

        protected abstract Root_name_9_name11Exception createException(String message);

        protected abstract Root_name_9_name11Exception createException(String message, Throwable cause);
    }

    protected Root_name_9_name11Exception(String message) {
        super(message);
    }

    protected Root_name_9_name11Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
