package com.rodrigodev.xgen.test.code.codeNameIsGeneratedFromErrorNameWhenNotSpecified_mixedCase;



/**
* Autogenerated by XGen on June 30, 2015.
*/
public class RootNameException extends RuntimeException {

    protected RootNameException(String message) {
        super(message);
    }
}
