package com.rodrigodev.xgen4j.test.integration.bedroom.bed.pillow_not_found;

import com.rodrigodev.xgen4j.test.integration.bedroom.bed.BedException;
import com.rodrigodev.xgen4j.test.integration.HouseException;
import com.rodrigodev.xgen4j.test.integration.ErrorCode;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class PillowNotFoundException extends BedException {

    public static final ExceptionType TYPE = new ExceptionType();

    protected PillowNotFoundException(ErrorCode errorCode, String message) {
        super(errorCode, message);
    }

    protected PillowNotFoundException(ErrorCode errorCode, String message, Throwable cause) {
        super(errorCode, message, cause);
    }

    private static class ExceptionType extends HouseException.ExceptionType {

        @Override
        protected HouseException createException(ErrorCode errorCode, String message) {
            return new PillowNotFoundException(errorCode, message);
        }

        @Override
        protected HouseException createException(ErrorCode errorCode, String message, Throwable cause) {
            return new PillowNotFoundException(errorCode, message, cause);
        }
    }
}
