package com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsNotSet.ue1;

import com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsNotSet.URootError;


import com.rodrigodev.xgen.test.generation_options.uncheckedExceptionsAreGeneratedWhenCorrespondingOptionIsNotSet.ErrorCode;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public abstract class UE1Error extends URootError {

    public static final ErrorCode CODE = new ErrorCode("u-e-1", URootError.CODE);


}
