package com.rodrigodev.xgen.test.code.codeNumericIdAndNumberAreGeneratedWhenSpecified;



/**
* Autogenerated by XGen on July 3, 2015.
*/
public class RootException extends RuntimeException {

    protected RootException(String message) {
        super(message);
    }
}
