package com.rodrigodev.xgen.test.code.codeNumericIdAndNumberAreGeneratedWhenSpecified;


import com.rodrigodev.xgen.test.code.codeNumericIdAndNumberAreGeneratedWhenSpecified.ErrorCode;


/**
* Autogenerated by XGen on July 2, 2015.
*/
public abstract class RootError {

    public static final ErrorCode CODE = new ErrorCode("root", 123);

}
