package com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.common9_name1.common9_name2;

import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.common9_name1.Common9Name1Exception;
import com.rodrigodev.xgen4j.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames.Root9NameException;

/**
 * Autogenerated by XGen4J on January 1, 0001.
 */
public class Common9Name2Exception extends Common9Name1Exception {



    protected Common9Name2Exception(String message) {
        super(message);
    }

    protected Common9Name2Exception(String message, Throwable cause) {
        super(message, cause);
    }
}
