package com.rodrigodev.xgen.test.integration.common.room;

import com.rodrigodev.xgen.test.integration.common.CommonException;

/**
* Autogenerated by XGen on June 29, 2015.
*/
public class RoomException extends CommonException {

    protected RoomException(String message) {
        super(message);
    }
}
