package com.rodrigodev.xgen.test.integration.common.room;

import com.rodrigodev.xgen.test.integration.common.CommonError;
import com.rodrigodev.xgen.test.integration.ErrorCode;


/**
* Autogenerated by XGen on July 3, 2015.
*/
public abstract class RoomError extends CommonError {

    public static final ErrorCode CODE = new ErrorCode("room", CommonError.CODE);

}
