package com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedWhenSpecified.e1;

import com.rodrigodev.xgen.test.code.codeIdAndNameAreGeneratedWhenSpecified.RootException;

/**
* Autogenerated by XGen on July 3, 2015.
*/
public class E1Exception extends RootException {

    protected E1Exception(String message) {
        super(message);
    }
}
