package com.rodrigodev.xgen.test.hierarchy;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class C1Exception extends RootException {

    protected C1Exception(String message) {
        super(message);
    }
}
