package com.rodrigodev.xgen.test.hierarchy;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class C3_1Exception extends C2Exception {

    protected C3_1Exception(String message) {
        super(message);
    }
}
