package com.rodrigodev.xgen.test.hierarchy;

/**
* Autogenerated by XGen on 25/05/15.
*/
public class C3_2Exception extends C2Exception {

    protected C3_2Exception(String message) {
        super(message);
    }
}
