package com.rodrigodev.xgen.test.hierarchy;

/**
* Autogenerated by XGen on 12/05/15.
*/
public abstract class E3_1Error extends E2Error {

    private static String MESSAGE_FORMAT = "ABCDE";

    public static void throwException() {
        throw new E3_1Exception(String.format(MESSAGE_FORMAT));
    }
}
