package com.rodrigodev.xgen.test.integration.common.appliance;

import com.rodrigodev.xgen.test.integration.common.CommonError;

/**
* Autogenerated by XGen on 12/05/15.
*/
public abstract class ApplianceError extends CommonError {

    private static String MESSAGE_FORMAT = "Something went wrong with %s appliance.";

    public static void throwException(String applianceName) {
        throw new ApplianceException(String.format(MESSAGE_FORMAT, applianceName));
    }
}
