package com.rodrigodev.xgen.test.integration.common.appliance;

import com.rodrigodev.xgen.test.integration.common.CommonException;

/**
* Autogenerated by XGen on June 30, 2015.
*/
public class ApplianceException extends CommonException {

    protected ApplianceException(String message) {
        super(message);
    }
}
