package com.rodrigodev.xgen.test.integration.common.appliance;

import com.rodrigodev.xgen.test.integration.common.CommonException;
import com.rodrigodev.xgen.test.integration.HouseException;

/**
* Autogenerated by XGen on July 6, 2015.
*/
public class ApplianceException extends CommonException {


    protected ApplianceException(String message) {
        super(message);
    }
}
